@CleanArchCQRS.API_HostAddress = http://localhost:5130

GET {{CleanArchCQRS.API_HostAddress}}/mangas
Accept: application/json

###

GET {{CleanArchCQRS.API_HostAddress}}/mangas/1
Accept: application/json

###
